services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
